"Skip pretending to be vi
set nocompatible

"Enable syntax and solarized colorscheme
syntax enable
set t_Co=256
colorscheme minimalist

"Display Hybrid  Line Numbers
set number relativenumber

"Open new vertical split windows on the right
"Open new split windows below
set splitright
set splitbelow

"Do not create backup and swap files
set nobackup
set nowritebackup
set noswapfile

"Disable Parenthesis Matching
set noshowmatch

"Code Folding
set foldmethod=manual
autocmd BufWinLeave *.* mkview
autocmd BufWinEnter *.* silent loadview

"Search down into subfolders
"Provides tab-completion for all file-related tasks
set path+=**

"Display all matching files when we tab complete
set wildmenu

"Tag Jumping
"Create the 'tags' file
" - Use ^] to jump to tag under cursor
" - Use g^] for ambiguous tags
" - Use ^t to jump back up the tag stack
command! MakeTags !ctags -R

" ----------- Key Mappings ---------

" Disabling Arrow Keys in Normal Mode
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" Disabling Arrow Keys in Insert Mode
inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>

" Custom Mapping for split navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Start of vim-plug Manager
call plug#begin()
	Plug 'vim-scripts/AutoClose'					"Autoclose paranthesis and quotations
	Plug 'scrooloose/nerdtree'						"File browser
	Plug 'SirVer/ultisnips'			    			"Ultisnips Snippets
	Plug 'thaerkh/vim-indentguides' 			"Indent Guide Lines
	Plug 'tpope/vim-fugitive'       			"Vim Plugin for Git
	Plug 'sheerun/vim-polyglot'     			"Language Syntax
	Plug 'vim-test/vim-test' 							"Testing within vim
	Plug 'vim-airline/vim-airline' 				"Vim Airline Status Bar
	Plug 'vim-airline/vim-airline-themes' "Vim Airline Theme
	"Plug 'lervag/vimtex'			"LaTeX filetype plugin
	"Plug 'tpope/vim-surround' "Matching Paranthesis and Tags
	"Plug 'alfredodeza/coveragepy.vim' "Coverage
call plug#end()
" End of vim-plug Managaer

" NERDTree Settings
nmap <C-f> :NERDTreeToggle<CR>
" enable line numbers and relative numbers in NERDTree
let NERDTreeShowLineNumbers=1
autocmd Filetype nerdtree setlocal relativenumber

"ultisnips settings
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
let g:UltiSnipsSnippetDirectories=['~/.vim/UltiSnips', 'UltiSnips']
let g:UltiSnipsEditSplit="vertical"

"vim-polyglot settings
let g:python_highlight_space_errors=0
let g:dart_style_guide=1

"vim-indentguides settings
let g:indentguides_spacechar='|'
let g:indentguides_tabchar='|'

"vim-test settings
let test#python#runner = 'pytest'
let test#dart#runner = 'fluttertest'
nmap <silent> tF :TestFile<CR>
nmap <silent> tN :TestNearest<CR>
nmap <silent> tL :TestLast<CR>
nmap <silent> tS :TestSuite<CR>
nmap <silent> tVF :TestFile --verbose<CR>
nmap <silent> tVN :TestNearest --verbose<CR>
nmap <silent> tVL :TestLast --verbose<CR>
nmap <silent> tVS :TestSuite<CR>

" vim-airline settings
let g:airline_theme='minimalist'
let g:airline_powerline_fonts = 1
let g:airline_left_sep = ''
let g:airline_right_sep = ''
let g:airline_section_b = '%-10.0{FugitiveStatusline()}'
let g:airline#extensions#whitespace#enabled = 0

"vimtex settings
"let g:tex_flavor='latex'
"let g:vimtex_view_method='zathura'
"let g:vimtex_quickfix_mode=0
"set conceallevel=1
"let g:tex_conceal='abdmg'
